// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GeneretePasswordInterface is an autogenerated mock type for the GeneretePasswordInterface type
type GeneretePasswordInterface struct {
	mock.Mock
}

// GeneretePassword provides a mock function with given fields: currentPw
func (_m *GeneretePasswordInterface) GeneretePassword(currentPw string) ([]byte, error) {
	ret := _m.Called(currentPw)

	if len(ret) == 0 {
		panic("no return value specified for GeneretePassword")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(currentPw)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(currentPw)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(currentPw)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGeneretePasswordInterface creates a new instance of GeneretePasswordInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGeneretePasswordInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *GeneretePasswordInterface {
	mock := &GeneretePasswordInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
