// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ValidateUtilityInterface is an autogenerated mock type for the ValidateUtilityInterface type
type ValidateUtilityInterface struct {
	mock.Mock
}

// LoginValidator provides a mock function with given fields: email, password
func (_m *ValidateUtilityInterface) LoginValidator(email string, password string) error {
	ret := _m.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for LoginValidator")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(email, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegisterValidator provides a mock function with given fields: username, email, password
func (_m *ValidateUtilityInterface) RegisterValidator(username string, email string, password string) error {
	ret := _m.Called(username, email, password)

	if len(ret) == 0 {
		panic("no return value specified for RegisterValidator")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(username, email, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewValidateUtilityInterface creates a new instance of ValidateUtilityInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidateUtilityInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ValidateUtilityInterface {
	mock := &ValidateUtilityInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
